<?php

namespace LemonWay\Examples;

use LemonWay\Models\Wallet;

require_once '../ExamplesBootstrap.php';
$api = ExamplesBootstrap::getApiInstance();

$myUrls = [
    'returnUrl' => ExamplesBootstrap::HOST . '/examples/MoneyIn_3D_Indirect/index.php',
    'cancelUrl' => ExamplesBootstrap::HOST . '/examples/MoneyIn_3D_Indirect/index.php',
    'errorUrl'  => ExamplesBootstrap::HOST . '/examples/MoneyIn_3D_Indirect/index.php',
    'cssUrl'    => ExamplesBootstrap::CSS_URL,
];

/**
 *      Case : Initialize a Money-in with 3D Secure and using secured Atos/BNP card forms
 *      Steps :
 *          - RegisterWallet : creating a customer wallet
 *          - MoneyInWebInit : initializing the payment. The output will be a token generated by Lemon Way, that you
 *          will need to pass to the WEBKIT Note :
 *          - Make sure you use a unique wkToken in input. You will use it to search for the payment when the customer
 *          comes back to your website after paying.
 *          - Atos/BNP test site has an invalid certificate. Please ignore the warning displayed by your browser and
 *          proceed.
 */

//RegisterWallet
$walletID = ExamplesDatas::getRandomId();
$res = $api->RegisterWallet([
    'wallet'          => $walletID,
    'clientMail'      => $walletID . '@mail.fr',
    'clientTitle'     => Wallet::MISTER,
    'clientFirstName' => 'Paul',
    'clientLastName'  => 'Dupond',
]);
if (isset($res->lwError)) {
    print 'Error, code ' . $res->lwError->CODE . ' : ' . $res->lwError->MSG;
} else {
    print '<br/>Wallet created : ' . $res->wallet->ID;
    $res2 = $api->MoneyInWebInit([
        'wkToken'        => ExamplesDatas::getRandomId(),
        'wallet'         => $walletID,
        'amountTot'      => '10.00',
        'amountCom'      => '2.00',
        'comment'        => 'comment',
        'returnUrl'      => urlencode($myUrls['returnUrl']),
        'cancelUrl'      => urlencode($myUrls['cancelUrl']),
        'errorUrl'       => urlencode($myUrls['errorUrl']),
        'autoCommission' => Wallet::NO_AUTO_COMMISSION,
    ]);
    if (isset($res2->lwError)) {
        print '<br/>Error, code ' . $res2->lwError->CODE . ' : ' . $res2->lwError->MSG;

        return;
    }
    print '<br/>Init successful. LWTOKEN: ' . $res2->lwXml->MONEYINWEB->TOKEN;
    $api->printCardForm($res2->lwXml->MONEYINWEB->TOKEN, $myUrls['cssUrl']);
}
